// ─────────────────────────────────────────────────────────────
// 타로 카드 78장 전체 데이터
// 비유: 타로 덱의 "백과사전" — 메이저 아르카나 22장 + 마이너 아르카나 56장
// 각 카드에는 영문/한국어 이름, 정방향·역방향 키워드, 상징적 설명이 담겨 있다.
// AI 해석 프롬프트에 카드 정보를 전달할 때 이 데이터를 활용한다.
// ─────────────────────────────────────────────────────────────

import { TarotCard } from '@/types/tarot'

/** 78장 타로 덱 전체 데이터 */
export const tarotDeck: TarotCard[] = [
  // ═══════════════════════════════════════════
  // 메이저 아르카나 (Major Arcana) — 22장
  // 인생의 큰 흐름과 영적 교훈을 상징한다
  // ═══════════════════════════════════════════
  {
    id: 'major_0',
    name: 'The Fool',
    nameKo: '바보',
    arcana: 'major',
    number: 0,
    uprightKeywords: ['새로운 시작', '자유', '순수', '모험'],
    reversedKeywords: ['무모함', '부주의', '방향 상실', '위험'],
    description: '절벽 끝에 선 여행자. 무한한 가능성과 새로운 시작을 상징하며, 두려움 없이 미지의 세계로 발걸음을 내딛는 순수한 용기를 나타낸다.',
  },
  {
    id: 'major_1',
    name: 'The Magician',
    nameKo: '마법사',
    arcana: 'major',
    number: 1,
    uprightKeywords: ['의지력', '창조', '집중', '기술'],
    reversedKeywords: ['속임수', '조작', '재능 낭비', '미숙'],
    description: '네 가지 원소를 다루는 마법사. 하늘과 땅을 잇는 중재자로서 의지와 능력으로 현실을 창조하는 힘을 상징한다.',
  },
  {
    id: 'major_2',
    name: 'The High Priestess',
    nameKo: '여사제',
    arcana: 'major',
    number: 2,
    uprightKeywords: ['직관', '내면의 지혜', '신비', '잠재의식'],
    reversedKeywords: ['비밀', '억눌린 감정', '내면 무시', '혼란'],
    description: '두 기둥 사이에 앉은 여사제. 숨겨진 진실과 내면의 목소리를 상징하며, 보이지 않는 것을 감지하는 직관의 힘을 나타낸다.',
  },
  {
    id: 'major_3',
    name: 'The Empress',
    nameKo: '여황제',
    arcana: 'major',
    number: 3,
    uprightKeywords: ['풍요', '모성', '자연', '창조력'],
    reversedKeywords: ['의존', '공허', '창조 정체', '과잉보호'],
    description: '자연 속의 여황제. 풍요와 생명력, 모성적 사랑을 상징하며, 삶의 아름다움과 풍성한 결실을 나타낸다.',
  },
  {
    id: 'major_4',
    name: 'The Emperor',
    nameKo: '황제',
    arcana: 'major',
    number: 4,
    uprightKeywords: ['권위', '안정', '리더십', '체계'],
    reversedKeywords: ['독재', '경직', '통제 과잉', '미성숙한 권위'],
    description: '왕좌에 앉은 황제. 질서와 구조, 강력한 리더십을 상징하며, 현실 세계에서의 지배력과 안정을 나타낸다.',
  },
  {
    id: 'major_5',
    name: 'The Hierophant',
    nameKo: '교황',
    arcana: 'major',
    number: 5,
    uprightKeywords: ['전통', '가르침', '신앙', '제도'],
    reversedKeywords: ['반항', '비전통', '독단', '교조주의'],
    description: '두 제자 앞에 선 교황. 전통적 가치와 영적 가르침을 상징하며, 지혜를 전달하는 스승의 역할을 나타낸다.',
  },
  {
    id: 'major_6',
    name: 'The Lovers',
    nameKo: '연인',
    arcana: 'major',
    number: 6,
    uprightKeywords: ['사랑', '조화', '선택', '결합'],
    reversedKeywords: ['불화', '유혹', '잘못된 선택', '불균형'],
    description: '천사 아래 서 있는 두 사람. 사랑과 결합뿐 아니라 인생의 중요한 선택의 갈림길을 상징한다.',
  },
  {
    id: 'major_7',
    name: 'The Chariot',
    nameKo: '전차',
    arcana: 'major',
    number: 7,
    uprightKeywords: ['승리', '의지', '전진', '자기 통제'],
    reversedKeywords: ['방향 상실', '좌절', '통제 불능', '공격성'],
    description: '두 스핑크스가 이끄는 전차. 강인한 의지와 자기 통제로 장애물을 극복하고 승리를 향해 나아가는 힘을 상징한다.',
  },
  {
    id: 'major_8',
    name: 'Strength',
    nameKo: '힘',
    arcana: 'major',
    number: 8,
    uprightKeywords: ['용기', '인내', '내면의 힘', '자비'],
    reversedKeywords: ['자기 의심', '약함', '두려움', '분노 폭발'],
    description: '사자를 다스리는 여인. 물리적 힘이 아닌 내면의 용기와 인내, 부드러운 강인함으로 본능을 다스리는 힘을 상징한다.',
  },
  {
    id: 'major_9',
    name: 'The Hermit',
    nameKo: '은둔자',
    arcana: 'major',
    number: 9,
    uprightKeywords: ['성찰', '고독', '내면 탐구', '지혜'],
    reversedKeywords: ['고립', '외로움', '은둔 과잉', '방향 상실'],
    description: '등불을 든 채 산 위에 선 노인. 세상에서 물러나 내면의 진실을 찾는 자기 성찰과 영적 탐구를 상징한다.',
  },
  {
    id: 'major_10',
    name: 'Wheel of Fortune',
    nameKo: '운명의 수레바퀴',
    arcana: 'major',
    number: 10,
    uprightKeywords: ['운명', '전환점', '행운', '순환'],
    reversedKeywords: ['불운', '저항', '변화 거부', '악순환'],
    description: '끊임없이 도는 수레바퀴. 운명의 순환과 변화, 예측할 수 없는 전환점을 상징하며, 삶의 흥망성쇠를 나타낸다.',
  },
  {
    id: 'major_11',
    name: 'Justice',
    nameKo: '정의',
    arcana: 'major',
    number: 11,
    uprightKeywords: ['공정', '진실', '균형', '인과응보'],
    reversedKeywords: ['불공정', '편견', '책임 회피', '부정직'],
    description: '저울과 검을 든 정의의 여신. 공정한 판단과 진실, 행위의 결과에 대한 책임을 상징한다.',
  },
  {
    id: 'major_12',
    name: 'The Hanged Man',
    nameKo: '매달린 사람',
    arcana: 'major',
    number: 12,
    uprightKeywords: ['희생', '새로운 관점', '인내', '내려놓음'],
    reversedKeywords: ['집착', '무의미한 희생', '지연', '이기심'],
    description: '나무에 거꾸로 매달린 사람. 자발적 희생과 관점의 전환을 통해 새로운 깨달음을 얻는 것을 상징한다.',
  },
  {
    id: 'major_13',
    name: 'Death',
    nameKo: '죽음',
    arcana: 'major',
    number: 13,
    uprightKeywords: ['변환', '끝', '새 시작', '해방'],
    reversedKeywords: ['변화 거부', '정체', '집착', '두려움'],
    description: '말 위의 죽음의 기사. 물리적 죽음이 아닌 근본적 변환과 끝을 통한 새로운 시작을 상징한다.',
  },
  {
    id: 'major_14',
    name: 'Temperance',
    nameKo: '절제',
    arcana: 'major',
    number: 14,
    uprightKeywords: ['균형', '조화', '인내', '중용'],
    reversedKeywords: ['불균형', '과잉', '충돌', '조급함'],
    description: '두 잔 사이에 물을 옮기는 천사. 대립하는 힘 사이에서 균형과 조화를 찾는 절제와 중용의 미덕을 상징한다.',
  },
  {
    id: 'major_15',
    name: 'The Devil',
    nameKo: '악마',
    arcana: 'major',
    number: 15,
    uprightKeywords: ['유혹', '속박', '집착', '물질주의'],
    reversedKeywords: ['해방', '자각', '속박 탈출', '자유 회복'],
    description: '사슬에 묶인 두 사람 위의 악마. 물질적 욕망과 중독, 자발적 속박을 상징하며, 내면의 그림자를 직면하라고 경고한다.',
  },
  {
    id: 'major_16',
    name: 'The Tower',
    nameKo: '탑',
    arcana: 'major',
    number: 16,
    uprightKeywords: ['붕괴', '충격', '계시', '해방'],
    reversedKeywords: ['변화 회피', '재난 지연', '내면 동요', '파괴 저항'],
    description: '번개에 맞아 무너지는 탑. 거짓된 구조의 갑작스러운 붕괴를 상징하며, 고통스럽지만 필요한 파괴를 통한 진실의 드러남을 나타낸다.',
  },
  {
    id: 'major_17',
    name: 'The Star',
    nameKo: '별',
    arcana: 'major',
    number: 17,
    uprightKeywords: ['희망', '영감', '평화', '치유'],
    reversedKeywords: ['절망', '자신감 상실', '단절', '희망 포기'],
    description: '별빛 아래 물을 붓는 여인. 폭풍 후의 고요한 희망과 영적 치유, 내면의 빛을 상징한다.',
  },
  {
    id: 'major_18',
    name: 'The Moon',
    nameKo: '달',
    arcana: 'major',
    number: 18,
    uprightKeywords: ['환상', '무의식', '불안', '직관'],
    reversedKeywords: ['혼란 해소', '두려움 극복', '진실 드러남', '명료'],
    description: '달빛 아래 두 개의 탑과 울부짖는 늑대. 무의식의 깊은 곳에서 올라오는 불안과 환상, 숨겨진 진실을 상징한다.',
  },
  {
    id: 'major_19',
    name: 'The Sun',
    nameKo: '태양',
    arcana: 'major',
    number: 19,
    uprightKeywords: ['기쁨', '성공', '활력', '긍정'],
    reversedKeywords: ['자만', '피로', '지연된 성공', '과시'],
    description: '밝은 태양 아래 말을 탄 아이. 순수한 기쁨과 성공, 삶의 활력과 긍정적 에너지를 상징하는 가장 밝은 카드이다.',
  },
  {
    id: 'major_20',
    name: 'Judgement',
    nameKo: '심판',
    arcana: 'major',
    number: 20,
    uprightKeywords: ['부활', '자각', '소명', '용서'],
    reversedKeywords: ['자기 비난', '후회', '소명 무시', '자기 기만'],
    description: '천사의 나팔 소리에 무덤에서 일어나는 사람들. 과거를 돌아보고 자신의 삶을 평가하는 영적 각성과 부활을 상징한다.',
  },
  {
    id: 'major_21',
    name: 'The World',
    nameKo: '세계',
    arcana: 'major',
    number: 21,
    uprightKeywords: ['완성', '통합', '성취', '여행'],
    reversedKeywords: ['미완성', '지연', '목표 미달', '정체'],
    description: '월계관 안에서 춤추는 인물. 한 순환의 완성과 통합, 모든 것이 하나로 어우러지는 궁극의 성취를 상징한다.',
  },

  // ═══════════════════════════════════════════
  // 마이너 아르카나 — 완드 (Wands) 14장
  // 불의 원소: 열정, 창조력, 의지, 행동을 상징한다
  // ═══════════════════════════════════════════
  {
    id: 'wands_1',
    name: 'Ace of Wands',
    nameKo: '완드 에이스',
    arcana: 'minor',
    suit: 'wands',
    number: 1,
    uprightKeywords: ['새로운 열정', '영감', '잠재력', '창조'],
    reversedKeywords: ['지연', '동기 상실', '방향 부재', '좌절'],
    description: '구름에서 나타난 손이 움트는 완드를 잡고 있다. 새로운 열정과 창조적 영감의 씨앗을 상징한다.',
  },
  {
    id: 'wands_2',
    name: 'Two of Wands',
    nameKo: '완드 2',
    arcana: 'minor',
    suit: 'wands',
    number: 2,
    uprightKeywords: ['계획', '결정', '미래 비전', '진취적'],
    reversedKeywords: ['우유부단', '두려움', '계획 부재', '현실 안주'],
    description: '성벽 위에서 지구본을 든 인물. 넓은 세계를 향한 계획과 미래에 대한 비전을 상징한다.',
  },
  {
    id: 'wands_3',
    name: 'Three of Wands',
    nameKo: '완드 3',
    arcana: 'minor',
    suit: 'wands',
    number: 3,
    uprightKeywords: ['확장', '전진', '기회 탐색', '성장'],
    reversedKeywords: ['지연', '장애물', '시야 협소', '실패'],
    description: '언덕 위에서 수평선을 바라보는 인물. 계획이 실행되고 성과가 확장되기 시작하는 단계를 상징한다.',
  },
  {
    id: 'wands_4',
    name: 'Four of Wands',
    nameKo: '완드 4',
    arcana: 'minor',
    suit: 'wands',
    number: 4,
    uprightKeywords: ['축하', '안정', '가정', '조화'],
    reversedKeywords: ['불안정', '갈등', '조화 부재', '미완성'],
    description: '화환으로 장식된 네 개의 완드 아래 축제. 가정의 안정과 기쁜 축하, 조화로운 관계를 상징한다.',
  },
  {
    id: 'wands_5',
    name: 'Five of Wands',
    nameKo: '완드 5',
    arcana: 'minor',
    suit: 'wands',
    number: 5,
    uprightKeywords: ['경쟁', '갈등', '도전', '긴장'],
    reversedKeywords: ['갈등 회피', '내면 갈등', '타협', '소모적 경쟁'],
    description: '다섯 명이 완드를 들고 다투는 장면. 건설적 경쟁과 갈등, 서로 다른 의견의 충돌을 상징한다.',
  },
  {
    id: 'wands_6',
    name: 'Six of Wands',
    nameKo: '완드 6',
    arcana: 'minor',
    suit: 'wands',
    number: 6,
    uprightKeywords: ['승리', '인정', '자신감', '리더십'],
    reversedKeywords: ['자만', '실패', '인정 부족', '체면 상실'],
    description: '월계관을 쓰고 말을 탄 승리자. 공적인 성공과 타인으로부터의 인정, 자신감 넘치는 전진을 상징한다.',
  },
  {
    id: 'wands_7',
    name: 'Seven of Wands',
    nameKo: '완드 7',
    arcana: 'minor',
    suit: 'wands',
    number: 7,
    uprightKeywords: ['방어', '인내', '도전 극복', '입장 고수'],
    reversedKeywords: ['포기', '압도당함', '자신감 부족', '후퇴'],
    description: '높은 곳에서 아래의 도전자들을 막아내는 인물. 불리한 상황에서도 자신의 입장을 지키는 강인함을 상징한다.',
  },
  {
    id: 'wands_8',
    name: 'Eight of Wands',
    nameKo: '완드 8',
    arcana: 'minor',
    suit: 'wands',
    number: 8,
    uprightKeywords: ['속도', '진행', '소식', '급진전'],
    reversedKeywords: ['지연', '혼란', '서두름', '잘못된 방향'],
    description: '하늘을 가르는 여덟 개의 완드. 빠른 전개와 소식의 도착, 장애물 없는 신속한 진행을 상징한다.',
  },
  {
    id: 'wands_9',
    name: 'Nine of Wands',
    nameKo: '완드 9',
    arcana: 'minor',
    suit: 'wands',
    number: 9,
    uprightKeywords: ['인내', '끈기', '경계', '회복력'],
    reversedKeywords: ['탈진', '의심', '방어 과잉', '포기 직전'],
    description: '상처를 입었지만 여전히 완드를 잡고 서 있는 인물. 시련을 겪고도 포기하지 않는 인내와 끈기를 상징한다.',
  },
  {
    id: 'wands_10',
    name: 'Ten of Wands',
    nameKo: '완드 10',
    arcana: 'minor',
    suit: 'wands',
    number: 10,
    uprightKeywords: ['과부하', '책임', '부담', '근면'],
    reversedKeywords: ['짐 내려놓기', '위임', '탈진', '해방'],
    description: '열 개의 완드를 힘겹게 나르는 인물. 과도한 책임과 부담을 상징하며, 짐을 나누거나 내려놓을 필요성을 시사한다.',
  },
  {
    id: 'wands_11',
    name: 'Page of Wands',
    nameKo: '완드 시종',
    arcana: 'minor',
    suit: 'wands',
    number: 11,
    uprightKeywords: ['탐험', '열정', '호기심', '새 소식'],
    reversedKeywords: ['방향 상실', '산만함', '자신감 부족', '지연'],
    description: '완드를 든 채 먼 곳을 바라보는 젊은이. 새로운 모험에 대한 열정과 호기심, 창조적 아이디어의 시작을 상징한다.',
  },
  {
    id: 'wands_12',
    name: 'Knight of Wands',
    nameKo: '완드 기사',
    arcana: 'minor',
    suit: 'wands',
    number: 12,
    uprightKeywords: ['모험', '대담함', '열정', '행동력'],
    reversedKeywords: ['성급함', '충동', '방향 없는 열정', '공격성'],
    description: '질주하는 말 위의 기사. 불같은 열정과 대담한 행동력으로 목표를 향해 돌진하는 에너지를 상징한다.',
  },
  {
    id: 'wands_13',
    name: 'Queen of Wands',
    nameKo: '완드 여왕',
    arcana: 'minor',
    suit: 'wands',
    number: 13,
    uprightKeywords: ['자신감', '카리스마', '따뜻함', '독립'],
    reversedKeywords: ['질투', '이기심', '자존감 부족', '지배적'],
    description: '해바라기와 함께 왕좌에 앉은 여왕. 따뜻한 카리스마와 자신감, 독립적이고 매력적인 리더십을 상징한다.',
  },
  {
    id: 'wands_14',
    name: 'King of Wands',
    nameKo: '완드 왕',
    arcana: 'minor',
    suit: 'wands',
    number: 14,
    uprightKeywords: ['비전', '리더십', '대담한 결단', '기업가정신'],
    reversedKeywords: ['독재', '무모함', '오만', '비현실적 기대'],
    description: '도마뱀이 새겨진 왕좌의 왕. 큰 비전과 대담한 리더십으로 사람들을 이끄는 카리스마적 지도자를 상징한다.',
  },

  // ═══════════════════════════════════════════
  // 마이너 아르카나 — 컵 (Cups) 14장
  // 물의 원소: 감정, 사랑, 관계, 직관을 상징한다
  // ═══════════════════════════════════════════
  {
    id: 'cups_1',
    name: 'Ace of Cups',
    nameKo: '컵 에이스',
    arcana: 'minor',
    suit: 'cups',
    number: 1,
    uprightKeywords: ['새로운 감정', '사랑', '직관', '영적 충만'],
    reversedKeywords: ['감정 억압', '공허', '사랑 거부', '차단'],
    description: '구름 속 손이 넘치는 성배를 들고 있다. 새로운 사랑과 감정적 충만, 영적 축복의 시작을 상징한다.',
  },
  {
    id: 'cups_2',
    name: 'Two of Cups',
    nameKo: '컵 2',
    arcana: 'minor',
    suit: 'cups',
    number: 2,
    uprightKeywords: ['파트너십', '상호 존중', '사랑', '유대'],
    reversedKeywords: ['불화', '단절', '불균형', '이별'],
    description: '서로에게 잔을 건네는 두 사람. 진정한 유대와 상호 존중에 기반한 파트너십을 상징한다.',
  },
  {
    id: 'cups_3',
    name: 'Three of Cups',
    nameKo: '컵 3',
    arcana: 'minor',
    suit: 'cups',
    number: 3,
    uprightKeywords: ['축하', '우정', '기쁨', '공동체'],
    reversedKeywords: ['과잉', '소외', '그룹 갈등', '방종'],
    description: '세 여인이 잔을 들고 춤추는 장면. 우정과 기쁨의 축하, 공동체의 따뜻함을 상징한다.',
  },
  {
    id: 'cups_4',
    name: 'Four of Cups',
    nameKo: '컵 4',
    arcana: 'minor',
    suit: 'cups',
    number: 4,
    uprightKeywords: ['무관심', '내면 성찰', '불만족', '명상'],
    reversedKeywords: ['새로운 인식', '기회 포착', '동기 부여', '행동'],
    description: '나무 아래 앉아 눈 앞의 잔을 외면하는 인물. 현재에 대한 불만족과 내면으로의 퇴각을 상징한다.',
  },
  {
    id: 'cups_5',
    name: 'Five of Cups',
    nameKo: '컵 5',
    arcana: 'minor',
    suit: 'cups',
    number: 5,
    uprightKeywords: ['상실', '슬픔', '후회', '실망'],
    reversedKeywords: ['회복', '수용', '앞으로 나아감', '용서'],
    description: '엎질러진 세 잔을 바라보며 뒤의 두 잔을 보지 못하는 인물. 상실의 슬픔 속에서 남은 것을 보지 못하는 상태를 상징한다.',
  },
  {
    id: 'cups_6',
    name: 'Six of Cups',
    nameKo: '컵 6',
    arcana: 'minor',
    suit: 'cups',
    number: 6,
    uprightKeywords: ['추억', '순수함', '향수', '나눔'],
    reversedKeywords: ['과거 집착', '미성숙', '비현실적 추억', '성장 거부'],
    description: '아이에게 꽃이 담긴 잔을 건네는 장면. 어린 시절의 순수한 추억과 무조건적인 나눔을 상징한다.',
  },
  {
    id: 'cups_7',
    name: 'Seven of Cups',
    nameKo: '컵 7',
    arcana: 'minor',
    suit: 'cups',
    number: 7,
    uprightKeywords: ['환상', '선택', '상상', '유혹'],
    reversedKeywords: ['현실 직시', '결정', '혼란 해소', '집중'],
    description: '구름 위에 떠 있는 일곱 잔의 환상. 수많은 가능성과 유혹 앞에서의 선택, 상상과 현실의 구분을 상징한다.',
  },
  {
    id: 'cups_8',
    name: 'Eight of Cups',
    nameKo: '컵 8',
    arcana: 'minor',
    suit: 'cups',
    number: 8,
    uprightKeywords: ['떠남', '탐색', '실망 극복', '내면 여행'],
    reversedKeywords: ['방황', '회피', '미련', '두려움'],
    description: '여덟 잔을 뒤로하고 산을 향해 떠나는 인물. 감정적 한계를 인정하고 더 깊은 의미를 찾아 떠나는 용기를 상징한다.',
  },
  {
    id: 'cups_9',
    name: 'Nine of Cups',
    nameKo: '컵 9',
    arcana: 'minor',
    suit: 'cups',
    number: 9,
    uprightKeywords: ['소원 성취', '만족', '행복', '감사'],
    reversedKeywords: ['탐욕', '불만족', '물질주의', '과시'],
    description: '아홉 잔 앞에서 만족스럽게 앉아 있는 인물. 소원의 성취와 감정적 충만, 삶에 대한 깊은 만족을 상징한다.',
  },
  {
    id: 'cups_10',
    name: 'Ten of Cups',
    nameKo: '컵 10',
    arcana: 'minor',
    suit: 'cups',
    number: 10,
    uprightKeywords: ['행복한 가정', '조화', '감정적 충만', '축복'],
    reversedKeywords: ['가정 불화', '불화', '기대 미달', '깨진 꿈'],
    description: '무지개 아래 행복한 가족. 가정의 평화와 감정적 완성, 사랑하는 이들과의 궁극적 조화를 상징한다.',
  },
  {
    id: 'cups_11',
    name: 'Page of Cups',
    nameKo: '컵 시종',
    arcana: 'minor',
    suit: 'cups',
    number: 11,
    uprightKeywords: ['감수성', '직관', '창의력', '메시지'],
    reversedKeywords: ['감정 미숙', '비현실적', '상상 과잉', '실망'],
    description: '잔 속 물고기에 놀란 젊은이. 예상치 못한 감정적 메시지와 풍부한 감수성, 창의적 직관을 상징한다.',
  },
  {
    id: 'cups_12',
    name: 'Knight of Cups',
    nameKo: '컵 기사',
    arcana: 'minor',
    suit: 'cups',
    number: 12,
    uprightKeywords: ['로맨스', '매력', '이상주의', '초대'],
    reversedKeywords: ['비현실적', '변덕', '감정 조종', '실망'],
    description: '잔을 들고 천천히 다가오는 기사. 사랑의 제안과 감정적 초대, 이상을 향한 로맨틱한 추구를 상징한다.',
  },
  {
    id: 'cups_13',
    name: 'Queen of Cups',
    nameKo: '컵 여왕',
    arcana: 'minor',
    suit: 'cups',
    number: 13,
    uprightKeywords: ['공감', '직관', '돌봄', '감성 지능'],
    reversedKeywords: ['감정 과잉', '의존', '자기 소홀', '변덕'],
    description: '물가에서 정교한 성배를 들고 있는 여왕. 깊은 공감과 직관, 타인을 돌보는 따뜻한 감성 지능을 상징한다.',
  },
  {
    id: 'cups_14',
    name: 'King of Cups',
    nameKo: '컵 왕',
    arcana: 'minor',
    suit: 'cups',
    number: 14,
    uprightKeywords: ['감정 성숙', '균형', '지혜', '관대함'],
    reversedKeywords: ['감정 억압', '냉담', '조종', '변덕'],
    description: '파도치는 바다 위 왕좌의 왕. 감정을 다스리면서도 풍부한 내면을 유지하는 성숙한 균형과 지혜를 상징한다.',
  },

  // ═══════════════════════════════════════════
  // 마이너 아르카나 — 소드 (Swords) 14장
  // 바람의 원소: 사고, 진실, 갈등, 커뮤니케이션을 상징한다
  // ═══════════════════════════════════════════
  {
    id: 'swords_1',
    name: 'Ace of Swords',
    nameKo: '소드 에이스',
    arcana: 'minor',
    suit: 'swords',
    number: 1,
    uprightKeywords: ['명확함', '진실', '돌파구', '새로운 사고'],
    reversedKeywords: ['혼란', '거짓', '오판', '잔인한 진실'],
    description: '구름 위 손이 왕관을 관통하는 검을 들고 있다. 진실의 명확한 인식과 새로운 지적 돌파구를 상징한다.',
  },
  {
    id: 'swords_2',
    name: 'Two of Swords',
    nameKo: '소드 2',
    arcana: 'minor',
    suit: 'swords',
    number: 2,
    uprightKeywords: ['결정 보류', '균형', '교착 상태', '직관 필요'],
    reversedKeywords: ['정보 과잉', '우유부단', '혼란', '감정적 결정'],
    description: '눈을 가린 채 두 검을 교차한 인물. 선택의 교착 상태에서 내면의 직관에 의지해야 하는 순간을 상징한다.',
  },
  {
    id: 'swords_3',
    name: 'Three of Swords',
    nameKo: '소드 3',
    arcana: 'minor',
    suit: 'swords',
    number: 3,
    uprightKeywords: ['마음의 상처', '슬픔', '이별', '배신'],
    reversedKeywords: ['치유', '용서', '회복', '과거 극복'],
    description: '비구름 아래 세 검에 관통된 심장. 사랑과 관계에서의 깊은 상처와 슬픔, 피할 수 없는 아픔을 상징한다.',
  },
  {
    id: 'swords_4',
    name: 'Four of Swords',
    nameKo: '소드 4',
    arcana: 'minor',
    suit: 'swords',
    number: 4,
    uprightKeywords: ['휴식', '회복', '명상', '재충전'],
    reversedKeywords: ['불안', '소진', '회복 거부', '강제 활동'],
    description: '교회 안 석관 위에 누운 기사. 전투 후의 필수적인 휴식과 내면의 재충전, 명상의 시간을 상징한다.',
  },
  {
    id: 'swords_5',
    name: 'Five of Swords',
    nameKo: '소드 5',
    arcana: 'minor',
    suit: 'swords',
    number: 5,
    uprightKeywords: ['갈등', '패배', '배신', '공허한 승리'],
    reversedKeywords: ['화해', '과거 교훈', '원한 해소', '용서'],
    description: '패배자들의 검을 줍는 승자. 겉보기 승리이지만 모두를 잃는 공허한 갈등과 배신을 상징한다.',
  },
  {
    id: 'swords_6',
    name: 'Six of Swords',
    nameKo: '소드 6',
    arcana: 'minor',
    suit: 'swords',
    number: 6,
    uprightKeywords: ['이동', '전환기', '치유 여정', '극복'],
    reversedKeywords: ['정체', '과거 집착', '미해결 문제', '저항'],
    description: '배를 타고 잔잔한 물로 향하는 인물들. 어려운 시기를 지나 평화로운 곳으로 이동하는 전환의 여정을 상징한다.',
  },
  {
    id: 'swords_7',
    name: 'Seven of Swords',
    nameKo: '소드 7',
    arcana: 'minor',
    suit: 'swords',
    number: 7,
    uprightKeywords: ['전략', '속임수', '은밀함', '기지'],
    reversedKeywords: ['양심의 가책', '자백', '계략 노출', '자기 기만'],
    description: '다섯 개의 검을 몰래 가져가는 인물. 교묘한 전략과 은밀한 행동, 때로는 속임수와 기만을 상징한다.',
  },
  {
    id: 'swords_8',
    name: 'Eight of Swords',
    nameKo: '소드 8',
    arcana: 'minor',
    suit: 'swords',
    number: 8,
    uprightKeywords: ['속박', '제한', '무력감', '자기 제한'],
    reversedKeywords: ['해방', '자기 인식', '새 관점', '자유'],
    description: '눈을 가린 채 검에 둘러싸인 인물. 실제보다 스스로 만든 정신적 감옥과 무력감을 상징한다.',
  },
  {
    id: 'swords_9',
    name: 'Nine of Swords',
    nameKo: '소드 9',
    arcana: 'minor',
    suit: 'swords',
    number: 9,
    uprightKeywords: ['불안', '악몽', '걱정', '죄책감'],
    reversedKeywords: ['회복', '극복', '도움 수용', '희망'],
    description: '침대에서 머리를 감싸고 괴로워하는 인물. 밤의 불안과 걱정, 과도한 정신적 고통을 상징한다.',
  },
  {
    id: 'swords_10',
    name: 'Ten of Swords',
    nameKo: '소드 10',
    arcana: 'minor',
    suit: 'swords',
    number: 10,
    uprightKeywords: ['끝', '바닥', '배신', '새벽 전 어둠'],
    reversedKeywords: ['회복', '재기', '최악 통과', '교훈'],
    description: '열 개의 검이 꽂힌 인물과 떠오르는 해. 가장 어두운 순간이지만 동시에 새로운 시작이 다가옴을 상징한다.',
  },
  {
    id: 'swords_11',
    name: 'Page of Swords',
    nameKo: '소드 시종',
    arcana: 'minor',
    suit: 'swords',
    number: 11,
    uprightKeywords: ['호기심', '날카로움', '관찰', '새로운 아이디어'],
    reversedKeywords: ['가십', '냉소', '미숙한 판단', '산만'],
    description: '바람 속에서 검을 든 젊은이. 날카로운 관찰력과 지적 호기심, 새로운 아이디어에 대한 열정을 상징한다.',
  },
  {
    id: 'swords_12',
    name: 'Knight of Swords',
    nameKo: '소드 기사',
    arcana: 'minor',
    suit: 'swords',
    number: 12,
    uprightKeywords: ['결단력', '직진', '지성', '신속한 행동'],
    reversedKeywords: ['성급함', '무모함', '공격성', '비논리적'],
    description: '전속력으로 질주하는 기사. 강한 신념과 결단력으로 목표를 향해 직진하는 지적 전사를 상징한다.',
  },
  {
    id: 'swords_13',
    name: 'Queen of Swords',
    nameKo: '소드 여왕',
    arcana: 'minor',
    suit: 'swords',
    number: 13,
    uprightKeywords: ['명석함', '독립', '직설', '경험에서 온 지혜'],
    reversedKeywords: ['냉정', '편견', '고독', '감정 차단'],
    description: '구름 위 왕좌에서 검을 든 여왕. 날카로운 지성과 풍부한 경험에서 나온 명석한 판단력을 상징한다.',
  },
  {
    id: 'swords_14',
    name: 'King of Swords',
    nameKo: '소드 왕',
    arcana: 'minor',
    suit: 'swords',
    number: 14,
    uprightKeywords: ['논리', '권위', '진실', '공정한 판단'],
    reversedKeywords: ['독재', '냉혹', '지나친 논리', '권력 남용'],
    description: '왕좌에서 검을 세운 왕. 객관적 논리와 공정한 판단, 진실을 추구하는 지적 권위를 상징한다.',
  },

  // ═══════════════════════════════════════════
  // 마이너 아르카나 — 펜타클 (Pentacles) 14장
  // 땅의 원소: 물질, 건강, 재정, 현실적 성취를 상징한다
  // ═══════════════════════════════════════════
  {
    id: 'pentacles_1',
    name: 'Ace of Pentacles',
    nameKo: '펜타클 에이스',
    arcana: 'minor',
    suit: 'pentacles',
    number: 1,
    uprightKeywords: ['새로운 기회', '번영', '물질적 시작', '잠재력'],
    reversedKeywords: ['기회 상실', '계획 부재', '재정 불안', '지연'],
    description: '구름 속 손이 금화를 든 채 정원 위에 떠 있다. 물질적 풍요와 새로운 재정적 기회의 시작을 상징한다.',
  },
  {
    id: 'pentacles_2',
    name: 'Two of Pentacles',
    nameKo: '펜타클 2',
    arcana: 'minor',
    suit: 'pentacles',
    number: 2,
    uprightKeywords: ['균형', '적응', '유연성', '우선순위'],
    reversedKeywords: ['불균형', '과부하', '혼란', '재정 불안'],
    description: '두 동전을 저글링하는 인물. 삶의 여러 영역 사이에서 유연하게 균형을 잡는 능력을 상징한다.',
  },
  {
    id: 'pentacles_3',
    name: 'Three of Pentacles',
    nameKo: '펜타클 3',
    arcana: 'minor',
    suit: 'pentacles',
    number: 3,
    uprightKeywords: ['팀워크', '숙련', '협업', '기술 인정'],
    reversedKeywords: ['갈등', '미숙', '소통 부재', '노력 무시'],
    description: '성당에서 일하는 장인과 의논하는 사람들. 전문적 기술과 협업을 통한 가치 있는 창작물을 상징한다.',
  },
  {
    id: 'pentacles_4',
    name: 'Four of Pentacles',
    nameKo: '펜타클 4',
    arcana: 'minor',
    suit: 'pentacles',
    number: 4,
    uprightKeywords: ['안정', '보존', '절약', '보안'],
    reversedKeywords: ['탐욕', '인색', '물질 집착', '변화 거부'],
    description: '네 동전을 꽉 쥔 인물. 물질적 안정과 보존을 추구하지만 지나치면 인색과 집착이 되는 양면성을 상징한다.',
  },
  {
    id: 'pentacles_5',
    name: 'Five of Pentacles',
    nameKo: '펜타클 5',
    arcana: 'minor',
    suit: 'pentacles',
    number: 5,
    uprightKeywords: ['궁핍', '어려움', '고립', '건강 문제'],
    reversedKeywords: ['회복', '도움 수용', '시련 극복', '희망'],
    description: '눈보라 속 교회 앞을 지나가는 두 빈민. 물질적 어려움과 소외감을 상징하지만, 가까이에 도움이 있음을 시사한다.',
  },
  {
    id: 'pentacles_6',
    name: 'Six of Pentacles',
    nameKo: '펜타클 6',
    arcana: 'minor',
    suit: 'pentacles',
    number: 6,
    uprightKeywords: ['관대함', '나눔', '공정', '베풂'],
    reversedKeywords: ['불공정', '빚', '조건부 관대', '의존'],
    description: '저울을 든 상인이 구걸자에게 동전을 나누는 장면. 관대한 나눔과 공정한 분배를 상징한다.',
  },
  {
    id: 'pentacles_7',
    name: 'Seven of Pentacles',
    nameKo: '펜타클 7',
    arcana: 'minor',
    suit: 'pentacles',
    number: 7,
    uprightKeywords: ['인내', '투자', '성과 평가', '장기 비전'],
    reversedKeywords: ['조급함', '보상 부재', '잘못된 투자', '포기'],
    description: '자란 작물을 바라보며 쉬는 농부. 오랜 노력의 성과를 돌아보고 장기적 투자의 결실을 기다리는 인내를 상징한다.',
  },
  {
    id: 'pentacles_8',
    name: 'Eight of Pentacles',
    nameKo: '펜타클 8',
    arcana: 'minor',
    suit: 'pentacles',
    number: 8,
    uprightKeywords: ['장인정신', '숙련', '근면', '기술 연마'],
    reversedKeywords: ['완벽주의', '무의미한 반복', '지루함', '근시안'],
    description: '동전을 하나하나 새기는 장인. 끊임없는 연습과 헌신을 통해 전문성을 갈고닦는 장인정신을 상징한다.',
  },
  {
    id: 'pentacles_9',
    name: 'Nine of Pentacles',
    nameKo: '펜타클 9',
    arcana: 'minor',
    suit: 'pentacles',
    number: 9,
    uprightKeywords: ['풍요', '독립', '자급자족', '성취'],
    reversedKeywords: ['과소비', '허영', '재정 의존', '외로움'],
    description: '풍성한 정원에서 매를 데리고 있는 여인. 자신의 노력으로 이룬 물질적 풍요와 독립적 성취를 상징한다.',
  },
  {
    id: 'pentacles_10',
    name: 'Ten of Pentacles',
    nameKo: '펜타클 10',
    arcana: 'minor',
    suit: 'pentacles',
    number: 10,
    uprightKeywords: ['유산', '가문', '장기적 성공', '안정'],
    reversedKeywords: ['가족 갈등', '재정 분쟁', '유산 문제', '불안정'],
    description: '부유한 가문의 여러 세대가 함께하는 장면. 세대를 이어가는 물질적 풍요와 가족의 유산을 상징한다.',
  },
  {
    id: 'pentacles_11',
    name: 'Page of Pentacles',
    nameKo: '펜타클 시종',
    arcana: 'minor',
    suit: 'pentacles',
    number: 11,
    uprightKeywords: ['학습', '새로운 기술', '기회', '성실'],
    reversedKeywords: ['게으름', '비현실적 목표', '집중 부족', '기회 낭비'],
    description: '동전을 조심스럽게 바라보는 젊은이. 새로운 기술을 배우려는 의지와 현실적 기회에 대한 진지한 탐구를 상징한다.',
  },
  {
    id: 'pentacles_12',
    name: 'Knight of Pentacles',
    nameKo: '펜타클 기사',
    arcana: 'minor',
    suit: 'pentacles',
    number: 12,
    uprightKeywords: ['근면', '인내', '책임감', '신뢰'],
    reversedKeywords: ['완고', '지루함', '비효율', '정체'],
    description: '경작지 위에 멈춰 선 기사. 화려하지 않지만 꾸준하고 신뢰할 수 있는 노력과 책임감을 상징한다.',
  },
  {
    id: 'pentacles_13',
    name: 'Queen of Pentacles',
    nameKo: '펜타클 여왕',
    arcana: 'minor',
    suit: 'pentacles',
    number: 13,
    uprightKeywords: ['실용', '풍요', '돌봄', '재정 감각'],
    reversedKeywords: ['자기 소홀', '물질 집착', '과보호', '불안'],
    description: '토끼와 함께 정원의 왕좌에 앉은 여왕. 실용적 지혜로 가정과 재정을 돌보는 따뜻한 풍요를 상징한다.',
  },
  {
    id: 'pentacles_14',
    name: 'King of Pentacles',
    nameKo: '펜타클 왕',
    arcana: 'minor',
    suit: 'pentacles',
    number: 14,
    uprightKeywords: ['부', '사업 수완', '안정', '풍요'],
    reversedKeywords: ['탐욕', '물질주의', '독점', '재정 실패'],
    description: '포도와 황소로 장식된 왕좌의 왕. 물질적 성공과 사업적 수완, 풍요로운 삶을 이끄는 현실적 지도자를 상징한다.',
  },
]
